FROM python:3.13.3-slim

WORKDIR /app
COPY rehydrate.py .
COPY services services
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080
ENTRYPOINT ["python", "rehydrate.py"]